### ISSUE TITLE
somthing wrong when attach zip files 

### ISSUE THREAD

**Issue by mustafaG9** [sidlatau/flutter_email_sender#114]
```
W/Bundle  ( 3771): Key android.intent.extra.TEXT expected ArrayList<java.lang.CharSequence> but value was of a different type.  The default value <null> was returned.
W/Bundle  ( 3771): Attempt to cast generated internal exception:
W/Bundle  ( 3771): java.lang.ClassCastException: Cannot cast java.lang.String to java.util.ArrayList
W/Bundle  ( 3771): 	at java.lang.Class.cast(Class.java:4109)
W/Bundle  ( 3771): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:404)
W/Bundle  ( 3771): 	at android.os.BaseBundle.getValue(BaseBundle.java:381)
W/Bundle  ( 3771): 	at android.os.BaseBundle.getArrayList(BaseBundle.java:1527)
W/Bundle  ( 3771): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1570)
W/Bundle  ( 3771): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1231)
W/Bundle  ( 3771): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:9306)
W/Bundle  ( 3771): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12363)
W/Bundle  ( 3771): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1871)
W/Bundle  ( 3771): 	at android.app.Activity.startActivityForResult(Activity.java:5589)
W/Bundle  ( 3771): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
W/Bundle  ( 3771): 	at android.app.Activity.startActivityForResult(Activity.java:5547)
W/Bundle  ( 3771): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:683)
W/Bundle  ( 3771): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.sendEmail(FlutterEmailSenderPlugin.kt:171)
W/Bundle  ( 3771): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onMethodCall(FlutterEmailSenderPlugin.kt:72)
W/Bundle  ( 3771): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/Bundle  ( 3771): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/Bundle  ( 3771): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/Bundle  ( 3771): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/Bundle  ( 3771): 	at android.os.Handler.handleCallback(Handler.java:958)
W/Bundle  ( 3771): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  ( 3771): 	at android.os.Looper.loopOnce(Looper.java:205)
W/Bundle  ( 3771): 	at android.os.Looper.loop(Looper.java:294)
W/Bundle  ( 3771): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
W/Bundle  ( 3771): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 3771): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
W/Bundle  ( 3771): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)



```

**Comment by mustafaG9** [comment]
duplicate of https://github.com/sidlatau/flutter_email_sender/issues/95
