### ISSUE TITLE
work on android but not on ios...

### ISSUE THREAD

**Issue by nitneuq33** [sidlatau/flutter_email_sender#27]
Hello I use the same example code on github, it's works on android but when I try to call send() I have nothing. I have error with snackbar but when I remove this part I have nothing. 

here is the snackbar error that I havn't with android 

```
Unhandled Exception: NoSuchMethodError: The method 'showSnackBar' was called on null.
Receiver: null
Tried calling: showSnackBar(Instance of 'SnackBar')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _menuscreenState.send (package:ouiquit/bottom.dart:8286:31)
<asynchronous suspension>
#2      _menuscreenState.build.<anonymous closure>.<anonymous closure> (package:ouiquit/bottom.dart:8682:13)
#3      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
#4      _menuscreenState.build.<anonymous closure> (package:ouiquit/bottom.dart:8681:11)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#9      TapGesture<…>
```

Here is my code 

```
String attachment;
  final _recipientController = TextEditingController(
    text: 'xxxx@xxxx.com',
  );

  final _subjectController = TextEditingController(text: '');

  final _bodyController = TextEditingController(
    text: '',
  );

  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  Future<void> send() async {
    final Email email = Email(
      body: _bodyController.text,
      subject: _subjectController.text,
      recipients: [_recipientController.text],
      attachmentPath: attachment,
    );

    String platformResponse;

    try {
      await FlutterEmailSender.send(email);
      platformResponse = '';
    } catch (error) {
      platformResponse = error.toString();
    }

    if (!mounted) return;

    _scaffoldKey.currentState.showSnackBar(SnackBar(
      content: Text(platformResponse),
    ));
  }
```

thank you

**Comment by sidlatau** [comment]
Looks like it is not a plugin problem. Check if _scaffoldKey is used in you Scaffold.
