### ISSUE TITLE
Using Flutter_email_sender with IOS 13.5.1 

### ISSUE THREAD

**Issue by Colt94** [sidlatau/flutter_email_sender#47]
I am now getting this error when sending an email on my flutter app using my Iphone 6s (IOS 13.5.1). I suspect it has to do with the IOS update because it worked with previous IOS versions. 
Anyone else experiencing this issue? Using xcode 11.

**2020-06-17 11:38:59.448606-0500 Runner[398:16848] [Common] [FBSSystemService][0x7292] Error handling open request for com.apple.mobilemail: <NSError: 0x2831d8960; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Un-trusted clients may not open applications in the background")."> {
    userInfo = {
        FBSOpenApplicationRequestID = 0x7292;
    }
    underlyingError = <NSError: 0x2831d8bd0; domain: FBSOpenApplicationErrorDomain; code: 3 (Security); reason: "Un-trusted clients may not open applications in the background.">;
}
2020-06-17 11:38:59.448870-0500 Runner[398:17071] [General] #MailServices <MSAccounts: 0x282b4eb00> (0) : <connection: 0x280bebb40> failed to send message <dictionary: 0x281aaea60> NSError Domain=MailServices Code=2
2020-06-17 11:39:00.305431-0500**

**Comment by enhnarang** [comment]
Hello Colt, thank you for posting this issue. I am facing the same problem, the android version works like a charm yet ios version email sender is not prompting to open the mailing apps.

**Comment by ganger1** [comment]
Same Issue

`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(not_available, No email clients found!, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      FlutterEmailSender.send (package:flutter_email_sender/flutter_email_sender.dart:10:21)
#3      _SettingsPageState.sendEmail (package:hadyah/features/presentation/pages/setting/settings_page.dart:60:30)
#4      _SettingsPageState.build.<anonymous closure>.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:150:41)
#5      SettingsState.whenPartial (package:hadyah/features/presentation/blocs/settings/settings_state.g.dart:174:24)
#6      _SettingsPageState.build.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:137:27)
#7      _BlocListenerBaseState._subscribe.<anonymous closure> (p<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(not_available, No email clients found!, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      FlutterEmailSender.send (package:flutter_email_sender/flutter_email_sender.dart:10:21)
#3      _SettingsPageState.sendEmail (package:hadyah/features/presentation/pages/setting/settings_page.dart:60:30)
#4      _SettingsPageState.build.<anonymous closure>.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:150:41)
#5      SettingsState.whenPartial (package:hadyah/features/presentation/blocs/settings/settings_state.g.dart:174:24)
#6      _SettingsPageState.build.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:137:27)
#7      _BlocListenerBaseState._subscribe.<anonymous closure> (p<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(not_available, No email clients found!, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      FlutterEmailSender.send (package:flutter_email_sender/flutter_email_sender.dart:10:21)
#3      _SettingsPageState.sendEmail (package:hadyah/features/presentation/pages/setting/settings_page.dart:60:30)
#4      _SettingsPageState.build.<anonymous closure>.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:145:43)
#5      SettingsState.whenPartial (package:hadyah/features/presentation/blocs/settings/settings_state.g.dart:168:27)
#6      _SettingsPageState.build.<anonymous closure> (package:hadyah/features/presentation/pages/setting/settings_page.dart:137:27)`

**Comment by Motero69** [comment]
I have the same problem in IOS:  the message I recived is : PlatformException(not_available, No email clients found!, null)

Any solutions?

**Comment by FetFrumos** [comment]
I have this issue on iOS. Any news?

**Comment by sarn0ld** [comment]
We have the same issue on iOS 14...

**Comment by erperejildo** [comment]
Same with iOS 13. Any solution yet?

**Comment by josephmangmang** [comment]
on ios not working. No email clients found!

**Comment by jaffamd** [comment]
I see how far back this thread goes, but for what it's worth, it's now January 2022 and this issue appears to be persistent. Android works fine after making the recommended change to AndroidManifest.xml, but iOS still gives the same error of "no email clients found". Anyone figure this out yet? Is it some kind of permissions issue? Something in the Info.plist?

**Comment by levi956** [comment]
Seems there is no fix. Is the project still actively maintained ?

**Comment by levi956** [comment]
Seems there has been no fix. Is there project still actively maintained?

**Comment by sidlatau** [comment]
For the error `No email clients found!` - this plugin does not work in an iOS simulator, because the simulator does not have an email client, plugin works only on real devices. Maybe that is the issue?

**Comment by IshchikGL** [comment]
@sidlatau it's not working on iPhone 7+ (iOS 13.3.1). I'm getting `PlatformException(not_available, No email clients found!, null, null)` but there are a default client and Gmail installed. Maybe it's expecting some default app to be configured (not sure it could be done on iOS13)

**Comment by clevertrevor** [comment]
Reproducible on an iPhone 13 Pro with iOS 16.6, and I have repro steps! @sidlatau 
100% reproducible when the iOS mail app is not logged in. Once logged in, I saw the new mail message modal pop up. The iPhone has Gmail installed, and the user's expectation would be for their preferred email client to open.

**Comment by Ahmadre** [comment]
> For the error `No email clients found!` - this plugin does not work in an iOS simulator, because the simulator does not have an email client, plugin works only on real devices. Maybe that is the issue?

It's also occuring on real devices.

**Comment by lukehutch** [comment]
This is occurring on a physical iPhone (one of my users' devices, iOS 17.x). The user reports that they uninstalled the Apple Mail app. They have the Gmail app installed, but the `flutter_email_sender` plugin does not seem to be able to send mail via Gmail.

**Comment by GregUAs** [comment]
@lukehutch

any solution for sending files in mail ? because url_launcher doesn't allow this feature...

**Comment by lukehutch** [comment]
@GregUAs there may be a special URL parameter for attachment path, but it will be platform-specific if it's even available at all. I don't know how to look up the URL spec for either Android or iOS.
