### ISSUE TITLE
Android app crashes: IllegalStateException: reply already submitted

### ISSUE THREAD

**Issue by zjamshidi** [sidlatau/flutter_email_sender#57]
Hello there,
Firstly, thanks for this outstanding plugin.
In my app, there is a "report an issue" menu that lets users send us emails using this plugin. If the user taps on this menu several times, only one of them is captured. However, I'm still getting these crashes. Would you please help me find the cause and fix it?
```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onActivityResult(FlutterEmailSenderPlugin.java:11)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:20)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:2)
       at android.app.Activity.dispatchActivityResult(Activity.java:7355)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4331)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4379)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)```

**Comment by sidlatau** [comment]
Looks like it was an issue with multiple plugin calls. I am closing it now, feel free to open a new one if the issue still exists.
