### ISSUE TITLE
error in gradle, error: resource android:attr/dialogCornerRadius not found

### ISSUE THREAD

**Issue by keshav1611** [sidlatau/flutter_email_sender#9]
I tried to use the dependency, but as soon as I add it in pubspec.yaml and run the app I get the following error.

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
C:\Users\kjethal\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\11a6953c6eb4e6c487d8965a46bf7400\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
C:\FlutterProject\email_sender\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
C:\Users\kjethal\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\11a6953c6eb4e6c487d8965a46bf7400\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.
    
C:\Users\kjethal\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\11a6953c6eb4e6c487d8965a46bf7400\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle build failed: 1`

**Comment by keshav1611** [comment]
Thanks, it is working now. But it is unable to access an attachment from the getApplicationDocumentsDirectory() path. Following is the error:

E/MethodChannel#flutter_email_sender(20680): Failed to handle method call
E/MethodChannel#flutter_email_sender(20680): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.example.clbrapp/app_flutter/Technical_Report.pdf
E/MethodChannel#flutter_email_sender(20680): 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
E/MethodChannel#flutter_email_sender(20680): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:418)
E/MethodChannel#flutter_email_sender(20680): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.sendEmail(FlutterEmailSenderPlugin.kt:85)
E/MethodChannel#flutter_email_sender(20680): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onMethodCall(FlutterEmailSenderPlugin.kt:30)
E/MethodChannel#flutter_email_sender(20680): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_email_sender(20680): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter_email_sender(20680): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_email_sender(20680): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_email_sender(20680): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_email_sender(20680): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_email_sender(20680): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_email_sender(20680): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_email_sender(20680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
